-- MySQL Script generated by MySQL Workbench
-- Thu Sep 30 23:24:34 2021
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DOARPI
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DOARPI` ;

-- -----------------------------------------------------
-- Schema DOARPI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DOARPI` ;
USE `DOARPI` ;

-- -----------------------------------------------------
-- Table `DOARPI`.`ESTADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DOARPI`.`ESTADO` ;

CREATE TABLE IF NOT EXISTS `DOARPI`.`ESTADO` (
  `idESTADO` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`idESTADO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOARPI`.`ENDERECO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DOARPI`.`ENDERECO` ;

CREATE TABLE IF NOT EXISTS `DOARPI`.`ENDERECO` (
  `idENDERECO` INT NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idENDERECO`),
  INDEX `estado_idx` (`estado` ASC),
  CONSTRAINT `estado`
    FOREIGN KEY (`estado`)
    REFERENCES `DOARPI`.`ESTADO` (`idESTADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOARPI`.`TELEFONE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DOARPI`.`TELEFONE` ;

CREATE TABLE IF NOT EXISTS `DOARPI`.`TELEFONE` (
  `idTELEFONE` INT NOT NULL,
  `cod_pais` VARCHAR(5) NOT NULL DEFAULT '+55',
  `ddd` VARCHAR(5) CHARACTER SET 'utf8' NOT NULL DEFAULT '(31)',
  `numero` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`idTELEFONE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOARPI`.`PROFILE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DOARPI`.`PROFILE` ;

CREATE TABLE IF NOT EXISTS `DOARPI`.`PROFILE` (
  `idPROFILE` INT NOT NULL,
  `user` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `tipo` VARCHAR(13) NOT NULL DEFAULT 'usuario',
  PRIMARY KEY (`idPROFILE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOARPI`.`PESSOAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DOARPI`.`PESSOAS` ;

CREATE TABLE IF NOT EXISTS `DOARPI`.`PESSOAS` (
  `idPESSOAS` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `pendereco` INT NULL,
  `ptelefone` INT NULL,
  `profile` INT NULL,
  `email` VARCHAR(45) NULL,
  `nascimento` DATETIME NULL,
  `doacao` INT NULL,
  PRIMARY KEY (`idPESSOAS`),
  INDEX `endereco_idx` (`pendereco` ASC),
  INDEX `telefone_idx` (`ptelefone` ASC),
  INDEX `profile_idx` (`profile` ASC),
  CONSTRAINT `enderecofk`
    FOREIGN KEY (`pendereco`)
    REFERENCES `DOARPI`.`ENDERECO` (`idENDERECO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `telefonefk`
    FOREIGN KEY (`ptelefone`)
    REFERENCES `DOARPI`.`TELEFONE` (`idTELEFONE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `profile`
    FOREIGN KEY (`profile`)
    REFERENCES `DOARPI`.`PROFILE` (`idPROFILE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOARPI`.`INSTITUICAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DOARPI`.`INSTITUICAO` ;

CREATE TABLE IF NOT EXISTS `DOARPI`.`INSTITUICAO` (
  `idINSTITUICAO` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `Iendereco` INT NULL,
  `Iresponsavel` INT NOT NULL,
  `Itelefone` INT NULL,
  `email` VARCHAR(45) NULL,
  `status` VARCHAR(14) NOT NULL DEFAULT 'nao validado',
  PRIMARY KEY (`idINSTITUICAO`),
  INDEX `endereco_idx` (`Iendereco` ASC),
  INDEX `responsavel_idx` (`Iresponsavel` ASC),
  INDEX `telefone_idx` (`Itelefone` ASC),
  CONSTRAINT `responsavel`
    FOREIGN KEY (`Iresponsavel`)
    REFERENCES `DOARPI`.`PESSOAS` (`idPESSOAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `endereco`
    FOREIGN KEY (`Iendereco`)
    REFERENCES `DOARPI`.`ENDERECO` (`idENDERECO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `telefone`
    FOREIGN KEY (`Itelefone`)
    REFERENCES `DOARPI`.`TELEFONE` (`idTELEFONE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOARPI`.`ITENS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DOARPI`.`ITENS` ;

CREATE TABLE IF NOT EXISTS `DOARPI`.`ITENS` (
  `idITENS` INT NOT NULL,
  `roupa` VARCHAR(45) NULL,
  `alimentos` VARCHAR(45) NULL,
  `dinheiro` DECIMAL NULL,
  `servico` VARCHAR(45) NULL,
  PRIMARY KEY (`idITENS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOARPI`.`DOACAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DOARPI`.`DOACAO` ;

CREATE TABLE IF NOT EXISTS `DOARPI`.`DOACAO` (
  `idDOACAO` INT NOT NULL,
  `itens` INT NULL,
  `data` DATETIME NOT NULL,
  `doador` INT NULL,
  `instituicao` INT NULL,
  PRIMARY KEY (`idDOACAO`),
  INDEX `itens_idx` (`itens` ASC),
  INDEX `instituicao_idx` (`instituicao` ASC),
  INDEX `doador_idx` (`doador` ASC),
  CONSTRAINT `itens`
    FOREIGN KEY (`itens`)
    REFERENCES `DOARPI`.`ITENS` (`idITENS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `instituicao`
    FOREIGN KEY (`instituicao`)
    REFERENCES `DOARPI`.`INSTITUICAO` (`idINSTITUICAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `doador`
    FOREIGN KEY (`doador`)
    REFERENCES `DOARPI`.`PESSOAS` (`idPESSOAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
